HC.Presentation/Models/Components/LayoutNavbarViewComponent.cs
using HC.Application.Models.VM;
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class LayoutNavbarViewComponent : ViewComponent
    {
        private readonly IAppUserService _appUserService;
        public LayoutNavbarViewComponent(IAppUserService appUserService) => _appUserService = appUserService;
        public async Task<IViewComponentResult> InvokeAsync(string userName)
        {
            if (userName != null)
            {
                var user = await _appUserService.GetByUser(userName);
                if (user == null)
                {
                    return View(new AppUserVM());
                }
                return View(user);
            }
            return View(new AppUserVM());
        }
    }
}

HC.Presentation/Models/Components/SideBarViewComponent.cs
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly ISubCategoryService _subCategoryService;
        public SideBarViewComponent(ISubCategoryService subCategoryService) => _subCategoryService = subCategoryService;
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var subCategories = await _subCategoryService.GetDefaultSubCategories();
            return View(subCategories);
        }
    }
}

HC.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="Hotcat, Restaurant, Food">
    <link rel="shortcut icon" href="/img/favicon.png">

    <title>HotCat Restaurant</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Zilla+Slab&display=swap"
          rel="stylesheet" />
</head>

<body>
    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a href="/Home/index" class="logo">HotCat<span> Restaurant</span></a>
            <!--logo end-->
            @await Component.InvokeAsync("LayoutNavbar",new{userName = User.Identity.Name})
        </header>
        <!--header end-->

        <!--sidebar start-->
        @await Component.InvokeAsync("SideBar")
        <!--sidebar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
            </section>
        </section>
        <!--main content end-->

        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                @DateTime.Now.Year &copy; FlatLab by HotcatRestaurant.
                <a href="#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/Content/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/js/jquery.scrollTo.min.js"></script>

    <!--common script for all pages-->
    <script src="~/Content/js/common-scripts.js"></script>

    @*@RenderSection("scripts",false)*@
</body>
</html>