HC.Presentation/Models/Components/LayoutNavbarViewComponent.cs
using HC.Application.Models.VM;
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class LayoutNavbarViewComponent : ViewComponent
    {
        private readonly IAppUserService _appUserService;
        public LayoutNavbarViewComponent(IAppUserService appUserService) => _appUserService = appUserService;
        public async Task<IViewComponentResult> InvokeAsync(string userName)
        {
            if (userName != null)
            {
                var user = await _appUserService.GetByUser(userName);
                if (user == null)
                {
                    return View(new AppUserVM());
                }
                return View(user);
            }
            return View(new AppUserVM());
        }
    }
}

HC.Presentation/Models/Components/ProfileViewComponent.cs
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class ProfileViewComponent : ViewComponent
    {
        private readonly IAppUserService _appUserService;
        public ProfileViewComponent(IAppUserService appUserService) => _appUserService = appUserService;
        public async Task<IViewComponentResult> InvokeAsync(string userName)
        {
            var user = await _appUserService.GetByUser(userName);
            return View(user);
        }
    }
}

HC.Presentation/Models/Components/SampleProductsViewComponent.cs
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class SampleProductsViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        public SampleProductsViewComponent(IProductService productService) => _productService = productService;
        public async Task<IViewComponentResult> InvokeAsync(Guid id)
        {
            var products = await _productService.GetProductsByCategory(id);
            return View(products);
        }
    }
}

HC.Presentation/Models/Components/SideBarViewComponent.cs
using HC.Application.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Models.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly ISubCategoryService _subCategoryService;
        public SideBarViewComponent(ISubCategoryService subCategoryService) => _subCategoryService = subCategoryService;
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var subCategories = await _subCategoryService.GetDefaultSubCategories();
            return View(subCategories);
        }
    }
}

HC.Presentation/Areas/Admin/Controllers/EmployeeController.cs
using FluentValidation.Results;
using HC.Application.Models.DTO;
using HC.Application.Service.Interface;
using HC.Application.Validation.FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "Admin")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;

        public EmployeeController(IEmployeeService employeeService, IDepartmentService departmentService)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _employeeService.GetEmployees());
        }

        #region Create
        public async Task<IActionResult> AddEmployee()
        {
            ViewBag.Departments = await _departmentService.GetDefaultDepartments();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddEmployee(CreateEmployeeDTO model)
        {
            ViewBag.Departments = await _departmentService.GetDefaultDepartments();
            CreateEmployeeDTOValidation validator = new CreateEmployeeDTOValidation();
            ValidationResult results = validator.Validate(model);
            if (results.IsValid)
            {
                var result = await _employeeService.Create(model);
                TempData["message"] = result;
                if (result == "Employee added!")
                {
                    return RedirectToAction("index");
                }
                return View(model);
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    TempData["message"] += "Error message: " + item.ErrorMessage + "\n";
                }
                return View(model);
            }
        }
        #endregion

        #region Update
        public async Task<IActionResult> UpdateEmployee(Guid id)
        {
            ViewBag.Departments = await _departmentService.GetDefaultDepartments();
            var employee = await _employeeService.GetById(id);
            return View(employee);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateEmployee(UpdateEmployeeDTO model)
        {
            ViewBag.Departments = await _departmentService.GetDefaultDepartments();
            UpdateEmployeeDTOValidation validator = new UpdateEmployeeDTOValidation();
            ValidationResult results = validator.Validate(model);
            if (results.IsValid)
            {
                TempData["message"] = await _employeeService.Update(model);
                return RedirectToAction("index");
            }
            foreach (var item in results.Errors)
            {
                TempData["message"] = "Error message: " + item.ErrorMessage + "\n";
            }
            return View(model);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> DeleteEmployee(Guid id)
        {
            TempData["message"] = await _employeeService.Delete(id);
            return RedirectToAction("index");
        } 
        #endregion
    }
}

HC.Presentation/Areas/Admin/Controllers/RoleController.cs
using HC.Application.Models.DTO;
using HC.Application.Service.Interface;
using HC.Application.Validation.FluentValidation;
using HC.Domain.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HC.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly RoleManager<AppUserRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(IRoleService roleService,RoleManager<AppUserRole> roleManager,UserManager<AppUser> userManager)
        {
            _roleService = roleService;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_roleService.GetRolesList());
        }

        #region CreateRole
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateRoleDTO model)
        {
            CreateRoleDTOValidation validator = new CreateRoleDTOValidation();
            var resultValidate = validator.Validate(model);
            if (resultValidate.IsValid)
            {
                var message = await _roleService.Create(model);
                TempData["message"] = message;
                if (message == "Role has been created!")
                    return RedirectToAction("Index");
                else
                    return View();
            }
            foreach (var item in resultValidate.Errors)
            {
                TempData["message"] += item.ErrorMessage + "\n";
            }
            return View(model);
        }
        #endregion

        #region DeleteRole
        public async Task<IActionResult> Delete(string id)
        {
            TempData["message"] = await _roleService.Delete(id);

            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(string id)
        {
            var role = await _roleService.GetById(id);
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdateRoleDTO model)
        {
            UpdateRoleDTOValidation validator = new UpdateRoleDTOValidation();
            var updatedRoleValidate = validator.Validate(model);
            if (updatedRoleValidate.IsValid)
            {
                TempData["message"] = await _roleService.Update(model);
                return RedirectToAction("Index");
            }
            foreach (var item in updatedRoleValidate.Errors)
            {
                TempData["message"] = item.ErrorMessage + "\n";
            }
            return View(model);
        }
        #endregion

        #region AssignedRole
        public async Task<IActionResult> AssignedRoleToUsers(string id)
        {
            AppUserRole role = await _roleManager.FindByIdAsync(id);

            List<AppUser> hasRole = new List<AppUser>();
            List<AppUser> hasNoRole = new List<AppUser>();

            foreach (AppUser user in _userManager.Users)
            {
                var result = await _userManager.IsInRoleAsync(user, role.Name); //Bu işlem için ConnectionString içerisine eklenmeli! => MultipleActiveResultSets=True; 
                if (result)
                    hasRole.Add(user);
                else
                    hasNoRole.Add(user);
            }

            return View(new AssignedRoleToUsersDTO { Role = role, HasRole = hasRole, HasNoRole = hasNoRole });
        }
        [HttpPost]
        public async Task<IActionResult> AssignedRoleToUsers(AssignedRoleToUsersDTO model)
        {
            IdentityResult result;


            foreach (string userId in model.UsersToBeAdded ?? new string[] { }) //Eğer kullanıcı eklenmezse array boş gelicek bu durumda null ref yememek için new string olarak yeni array açıldı.
            {
                AppUser user = await _userManager.FindByIdAsync(userId); //Arraydaki id den kullanıcıyı çek
                result = await _userManager.AddToRoleAsync(user, model.Role.Name); // çektiğin kullanıcıya belirtilen rolü ver.
            }

            foreach (string userId in model.UsersToBeDeleted ?? new string[] { })
            {
                AppUser user = await _userManager.FindByIdAsync(userId);
                result = await _userManager.RemoveFromRoleAsync(user, model.Role.Name); // kullanıcıdan belirtilen rolü sil.
            }

            return RedirectToAction("Index");
        } 
        #endregion

    }
}

HC.Presentation/Views/Shared/Components/SideBar/Default.cshtml
@model List<SubCategoryVM>

<aside>
    <div id="sidebar" class="nav-collapse ">
        <ul class="sidebar-menu" id="nav-accordion">
            <li>
                <a class="active" href="/Home/index">
                    <i class="icon-dashboard"></i>
                    <span>Anasayfa</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;">
                    <i class="icon-sitemap"></i>
                    <span>Categories</span>
                </a>
                <ul class="sub">
                    <li><a asp-action="index" asp-controller="Home" asp-area="" asp-route-id="">All Menus</a></li>
                    @foreach (var item in Model)
                    {
                        <li class="sub-menu">
                            <a href="boxed_page.html">@item.CategoryName</a>
                            <ul class="sub">
                                <li><a asp-action="index" asp-controller="home" asp-area="" asp-route-id="@item.ID">@item.SubCategoryName</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="icon-glass"></i>
                        <span>Admin Page</span>
                    </a>
                    <ul class="sub">
                        <li><a asp-area="admin" asp-controller="product" asp-action="index">Products</a></li>
                        <li><a asp-area="admin" asp-controller="category" asp-action="index">Categories</a></li>
                        <li><a asp-area="admin" asp-controller="subcategory" asp-action="index">SubCategories</a></li>
                        <li><a asp-area="admin" asp-controller="Employee" asp-action="index">Employees</a></li>
                        <li><a asp-area="admin" asp-controller="department" asp-action="index">Departments</a></li>
                        <li><a asp-area="admin" asp-controller="order" asp-action="index">Orders</a></li>
                        <li><a asp-area="admin" asp-controller="Role" asp-action="index">Assigned Role</a></li>
                    </ul>
                </li>
            }
            else if (User.IsInRole("Waiter") || User.IsInRole("Sales"))
            {
                <li>
                    <a asp-action="index" asp-controller="Home" asp-area="Waiter">
                        <i class="icon-bolt"></i>
                        <span>Waiter Page</span>
                    </a>
                </li>
            }
            else if (User.IsInRole("Purchase"))
            {
                <li>
                    <a asp-action="index" asp-controller="Home" asp-area="Purchase">
                        <i class="icon-bolt"></i>
                        <span>Purchase Page</span>
                    </a>
                </li>
            }
            <li>
                <a asp-action="AboutUs" asp-controller="Home" asp-area="">
                    <i class="icon-bookmark-empty"></i>
                    <span>About Us</span>
                </a>
            </li>
            <li>
                <a asp-action="Rezervation" asp-controller="Home" asp-area="">
                    <i class=" icon-phone-sign"></i>
                    <span>Rezervation</span>
                </a>
            </li>
        </ul>
    </div>
</aside>